name: Run Laravel Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root 
          MYSQL_DATABASE: docker_app
          MYSQL_USER: gallego
          MYSQL_PASSWORD: 
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Composer
        run: composer install

      - name: Create .env file
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_DATABASE=docker_app" >> .env
          echo "DB_USERNAME=gallego" >> .env
          echo "DB_PASSWORD=your_password" >> .env # Asegúrate de definir la contraseña

      - name: Generate application key
        run: php artisan key:generate

      - name: Set up Docker Compose
        run: |
          docker compose up -d --build

      - name: Wait for services to start
        run: |
          sleep 30

      - name: Run migrations
        run: |
          docker compose exec web php artisan migrate --force

      - name: Run seeders
        run: |
          docker compose exec web php artisan db:seed --force

      - name: Run integration tests
        run: |
          docker compose exec web php artisan test --testsuite=Feature

      - name: Simulate Deployment
        if: ${{ success() }}
        run: |
          echo "Deployment simulated: All tests passed!"