name: Run Laravel Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root 
          MYSQL_DATABASE: docker_app
          MYSQL_USER: gallego
        ports:
          - 3308:3306
        healthcheck:  # Cambié 'options' a 'healthcheck'
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, ctype, json, tokenizer, xml
          ini-values: post_max_size=256M, max_execution_time=300

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create .env file
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_DATABASE=docker_app" >> .env
          echo "DB_USERNAME=gallego" >> .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Set up Docker Compose
        run: |
          docker compose up -d --build

      - name: Wait for services to start
        run: |
          sleep 30

      - name: Run migrations
        run: |
          docker compose exec web php artisan migrate --force

      - name: Run seeders
        run: |
          docker compose exec web php artisan db:seed --force

      - name: Run integration tests
        run: |
          docker compose exec web php artisan test --testsuite=Feature

      - name: Simulate Deployment
        if: ${{ success() }}
        run: |
          echo "Deployment simulated: All tests passed!"